#!/bin/bash
 function disable_bt {
            echo "Detected Raspberry Pi 3...Disabling Bluetooth"
            if grep -q pi3-disable-bt "/boot/config.txt"; then
                echo 'Bluetooth Disabled'
            else
            echo 'dtoverlay=pi3-disable-bt' | sudo tee -a /boot/config.txt
                echo 'Bluetooth Disabled'
            fi
            sudo systemctl disable hciuart
           }


echo "Lora Gateway - Installation"
echo "============================"
sleep 2

echo -e "\n\nInstalling git..."
sudo apt-get update
sudo apt-get install -y git
sleep 1

sudo raspi-config nonint do_spi 0 ;; 

echo -e "\n\nInstalling Wiring Pi"
echo "===================="
sleep 3
cd
git clone git://git.drogon.net/wiringPi
cd wiringPi
./build

echo -e "\n\nInstalling SSDV"
echo "==============="
sleep 3
cd
git clone https://github.com/fsphil/ssdv.git
cd ssdv
sudo make install

sudo apt-get install libcurl4-openssl-dev

sudo apt-get install libncurses5-dev

cd ~
git clone https://github.com/PiInTheSky/lora-gateway.git
cd lora-gateway
make

cd ~/lora-gateway
